### ISSUE TITLE
Error adding entities for domain sensor (Home Assistant 2023.6.0)

### ISSUE THREAD

**Issue by oscarrdg** [vortizhe/home-assistant-ingeteam-modbus#4]
I get following error:

Logger: homeassistant.components.sensor
Source: components/integration/sensor.py:391
Integration: Sensor (documentation, issues)
First occurred: 6:05:38 PM (2 occurrences)
Last logged: 6:05:38 PM

Error adding entities for domain sensor with platform ingeteam_modbus
Error while setting up ingeteam_modbus platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 749, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 850, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 657, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/integration/sensor.py", line 391, in extra_state_attributes
    ATTR_SOURCE_ID: self._source_entity,
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'CalculatedEnergySensor' object has no attribute '_source_entity'

**Comment by vortizhe** [comment]
Fixed on c48ee9c68841a5a8617bd2ec30c071fe2d2416cd and released under v0.2.1 version
